GRANT USAGE ON SCHEMA public TO bytemarket_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO bytemarket_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO bytemarket_app;

ALTER DEFAULT PRIVILEGES FOR ROLE bytemarket_admin IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO bytemarket_app;

ALTER DEFAULT PRIVILEGES FOR ROLE bytemarket_admin IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO bytemarket_app;
